/*********************************************************************
 * @fn      		  - I2C_EV_IRQHandling
 *
 * @brief             -
 *
 * @param[in]         -
 * @param[in]         -
 * @param[in]         -
 *
 * @return            -
 *
 * @Note              -  Interrupt handling for different I2C events (refer SR1)

 */


void I2C_EV_IRQHandling(I2C_Handle_t *pI2CHandle)
{

	//Interrupt handling for both master and slave mode of a device

	
	//1. Handle For interrupt generated by SB event
	//	Note : SB flag is only applicable in Master mode
	
	//2. Handle For interrupt generated by ADDR event 
	//Note : When master mode : Address is sent 
	//		 When Slave mode   : Address matched with own address 
	
	//3. Handle For interrupt generated by BTF(Byte Transfer Finished) event  
	
	//4. Handle For interrupt generated by STOPF event 
	// Note : Stop detection flag is applicable only slave mode . For master this flag will never be set
		
	//5. Handle For interrupt generated by TXE event 
	
	//6. Handle For interrupt generated by RXNE event 

}
